--create database racuni;
--use racuni;
--create table racun(
--sifra int primary key;
--rednibroj int;
--datum datetime
--kupac varchar (20);
--placeno int
--);
--create table stavkeracuna(
--racun int
--artikl int
--cijena int
--kolicina int
--popust int
--)
